# Generated by Django 2.2.10 on 2021-09-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('quiz', '0002_auto_20210927_2036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz')),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['quiz'],
            },
        ),
        migrations.AddIndex(
            model_name='answers',
            index=models.Index(fields=['quiz'], name='quiz_idx'),
        ),
        migrations.AddIndex(
            model_name='answers',
            index=models.Index(fields=['value'], name='value_idx'),
        ),
        migrations.AddIndex(
            model_name='answers',
            index=models.Index(fields=['question'], name='question_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('quiz', 'question')},
        ),
    ]
