# Generated by Django 2.2.10 on 2021-09-27 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('exception_date', models.DateField()),
                ('offer_to_set', models.BooleanField(default=False)),
                ('replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='questions.Question')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
