# Generated by Django 2.2.10 on 2021-09-27 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quize',
            new_name='Quiz',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Quiz',
        ),
    ]
